[formatter.fourmolu]
command = "fourmolu"
options = ["--mode", "inplace"]
includes = ["src/**/*.hs", "app/**/*.hs", "tests/**/*.hs"]

[formatter.elm-format]
command = "elm-format"
options = ["--yes"]
includes = ["app/**/*.elm", "src/**/*.elm"]
