"""
Brand color configuration for Suomen Palikkaharrastajat ry.
Edit the values here — everything is regenerated by `make`.
"""

# ── Logo mark colors ──────────────────────────────────────────────────────────
FEATURE_COLOR   = '#05131D'   # LEGO Black  (features: eyes, brows, smile)
HIGHLIGHT_COLOR = '#FFFFFF'   # LEGO White  (eye highlights)

# ── Subtitle text colors ──────────────────────────────────────────────────────
SUBTITLE_ON_LIGHT = '#05131D'   # dark text on light backgrounds
SUBTITLE_ON_DARK  = '#FFFFFF'   # white text on dark backgrounds

# ── Dark theme background ──────────────────────────────────────────────────────
DARK_BG = '#05131D'   # LEGO Black

# ── Association name ──────────────────────────────────────────────────────────
ASSOCIATION_NAME = 'Suomen Palikkaharrastajat ry'

# ── LEGO skin tone colors ─────────────────────────────────────────────────────
# Used for the colorful variant and horizontal logo.
SKIN_TONES = [
    '#F2CD37',  # Yellow       (classic minifig)
    '#F6D7B3',  # Light Nougat (light skin)
    '#CC8E69',  # Nougat       (medium skin)
    '#AD6140',  # Dark Nougat  (dark skin)
]

# ── Rainbow colors (sourced from colors.csv) ─────────────────────────────────
RAINBOW_COLORS = [
    '#F2705E',  # Salmon          (id 12)   – red
    '#F9BA61',  # Light Orange    (id 125)  – orange
    '#F2CD37',  # Yellow          (id 14)   – yellow
    '#73DCA1',  # Medium Green    (id 74)   – green
    '#9FC3E9',  # Bright Light Blue (id 212) – blue
    '#9195CA',  # Light Lilac     (id 1093) – indigo
    '#AC78BA',  # Medium Lavender (id 30)   – violet
]

# ── Subtitle color per variant ────────────────────────────────────────────────
# Maps variant stem to subtitle text color.
SUBTITLE_COLOR = {
    'minifig-colorful': SUBTITLE_ON_LIGHT,
    'horizontal':       SUBTITLE_ON_LIGHT,
}
