{-# LANGUAGE OverloadedStrings #-}

-- | Generate src/Brand/Generated.elm from Brand.Colors constants.
-- No ADT, no intermediate representation — functions emit Text directly,
-- following the same pattern as planet's ElmGen.hs.
module Brand.ElmGen (generateBrandModule) where

import Brand.Colors
import Data.Text (Text)
import qualified Data.Text as T

-- | Generate the complete Elm source for Brand.Generated.
generateBrandModule :: Text
generateBrandModule =
    T.unlines
        [ "module Brand.Generated exposing (..)"
        , ""
        , "-- Generated by logo-gen. Do not edit by hand."
        , ""
        , "associationName : String"
        , "associationName ="
        , "    " <> renderString associationName
        , ""
        , "featureColor : String"
        , "featureColor ="
        , "    " <> renderString (unHex featureColor)
        , ""
        , "highlightColor : String"
        , "highlightColor ="
        , "    " <> renderString (unHex highlightColor)
        , ""
        , "darkBackground : String"
        , "darkBackground ="
        , "    " <> renderString (unHex darkBg)
        , ""
        , "logoBaseUrl : String"
        , "logoBaseUrl ="
        , "    " <> renderString "https://logo.palikkaharrastajat.fi"
        , ""
        , "type alias SkinTone ="
        , "    { id : String, name : String, hex : String }"
        , ""
        , "skinTones : List SkinTone"
        , "skinTones ="
        , renderSkinToneList skinTones
        , ""
        , "type alias RainbowColor ="
        , "    { id : String, name : String, hex : String, description : String }"
        , ""
        , "rainbowColors : List RainbowColor"
        , "rainbowColors ="
        , renderRainbowList rainbowColors
        ]

-- ── Helpers ──────────────────────────────────────────────────────────────────

unHex :: Hex -> Text
unHex (Hex t) = t

-- | Wrap in Elm double-quoted string with escaping.
renderString :: Text -> Text
renderString t = "\"" <> escapeElmString t <> "\""

-- | Escape special characters for Elm string literals.
escapeElmString :: Text -> Text
escapeElmString = T.concatMap escapeChar
  where
    escapeChar '\\' = "\\\\"
    escapeChar '"' = "\\\""
    escapeChar '\n' = "\\n"
    escapeChar '\r' = "\\r"
    escapeChar '\t' = "\\t"
    escapeChar c = T.singleton c

-- | Render [(id, name, Hex)] as an Elm list of records.
renderSkinToneList :: [(Text, Text, Hex)] -> Text
renderSkinToneList [] = "    []"
renderSkinToneList items =
    T.unlines $
        ["    [ " <> renderSkinTone (head items)]
            ++ map (\i -> "    , " <> renderSkinTone i) (tail items)
            ++ ["    ]"]

renderSkinTone :: (Text, Text, Hex) -> Text
renderSkinTone (i, n, Hex h) =
    T.concat
        [ "{ id = "
        , renderString i
        , ", name = "
        , renderString n
        , ", hex = "
        , renderString h
        , " }"
        ]

-- | Render [(id, name, Hex, desc)] as an Elm list of records.
renderRainbowList :: [(Text, Text, Hex, Text)] -> Text
renderRainbowList [] = "    []"
renderRainbowList items =
    T.unlines $
        ["    [ " <> renderRainbowColor (head items)]
            ++ map (\i -> "    , " <> renderRainbowColor i) (tail items)
            ++ ["    ]"]

renderRainbowColor :: (Text, Text, Hex, Text) -> Text
renderRainbowColor (i, n, Hex h, d) =
    T.concat
        [ "{ id = "
        , renderString i
        , ", name = "
        , renderString n
        , ", hex = "
        , renderString h
        , ", description = "
        , renderString d
        , " }"
        ]
