{-# LANGUAGE OverloadedStrings #-}

{- | Generate public/brand.css — the canonical CSS design system file.
Consumer projects copy this file locally and @import it in their CSS.
Note: Tailwind v4 requires @theme to be in the locally-processed file;
importing from a CDN URL does not propagate @theme tokens.
-}
module Guide.CssGen (generateBrandCss) where

import Data.Maybe (mapMaybe)
import Data.Text (Text)
import Data.Text qualified as T
import Guide.Types
import Numeric (showFFloat)

generateBrandCss :: DesignGuide -> Text
generateBrandCss dg =
    T.concat
        [ cssHeader
        , cssFontFace (dgTypography dg)
        , cssTheme dg
        , cssTypeUtilities (dgTypography dg)
        , cssBaseLayer
        , cssReducedMotion
        , cssSharedComponents
        ]

-- ---------------------------------------------------------------------------
-- Header
-- ---------------------------------------------------------------------------

cssHeader :: Text
cssHeader =
    T.unlines
        [ "/* brand.css \x2014 Suomen Palikkaharrastajat ry design system"
        , " * Generated by brand-gen. Consumer projects import this file locally."
        , " * Do NOT import from a CDN URL \x2014 Tailwind v4 requires @theme to be in the"
        , " * locally processed file. Copy this file and import it in your project CSS."
        , " */"
        , ""
        ]

-- ---------------------------------------------------------------------------
-- @font-face
-- ---------------------------------------------------------------------------

cssFontFace :: TypographyConfig -> Text
cssFontFace tc =
    T.unlines
        [ "@font-face {"
        , "  font-family: \"" <> head (tcFontFamily tc) <> "\";"
        , "  src: url(\"" <> tcFontFile tc <> "\") format(\"truetype\");"
        , "  font-weight: 100 900;"
        , "  font-style: normal;"
        , "  font-display: swap;"
        , "}"
        , ""
        ]

-- ---------------------------------------------------------------------------
-- @theme block
-- ---------------------------------------------------------------------------

cssTheme :: DesignGuide -> Text
cssTheme dg =
    let m = dgMeta dg
        tc = dgTypography dg
        mc = dgMotion dg
        fontStack = "\"" <> head (tcFontFamily tc) <> "\", " <> T.intercalate ", " (tail (tcFontFamily tc))
     in T.unlines $
            [ "@theme {"
            , "  /* \x2500\x2500 Brand core \x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500 */"
            , "  --color-brand:              " <> hexText (metaFeatureColor m) <> ";"
            , "  --color-brand-yellow:       #FAC80A;"
            , "  --color-brand-red:          " <> semHex dg "colorBrandRed" <> ";"
            , ""
            , "  /* \x2500\x2500 Nougat palette \x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500 */"
            ]
                ++ nougatLines dg
                ++ [ ""
                   , "  /* \x2500\x2500 Semantic text \x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500 */"
                   , "  --color-text-primary: " <> semHex dg "colorTextPrimary" <> ";"
                   , "  --color-text-on-dark: " <> semHex dg "colorTextOnDark" <> ";"
                   , "  --color-text-muted:   " <> semHex dg "colorTextMuted" <> ";"
                   , "  --color-text-subtle:  " <> semHex dg "colorTextSubtle" <> ";"
                   , ""
                   , "  /* \x2500\x2500 Semantic backgrounds \x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500 */"
                   , "  --color-bg-page:   " <> semHex dg "colorBgPage" <> ";"
                   , "  --color-bg-dark:   " <> semHex dg "colorBgDark" <> ";"
                   , "  --color-bg-subtle: " <> semHex dg "colorBgSubtle" <> ";"
                   , "  --color-bg-accent: " <> semHex dg "colorBgAccent" <> ";"
                   , ""
                   , "  /* \x2500\x2500 Semantic borders \x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500 */"
                   , "  --color-border-default: " <> semHex dg "colorBorderDefault" <> ";"
                   , "  --color-border-brand:   " <> semHex dg "colorBorderBrand" <> ";"
                   , ""
                   , "  /* \x2500\x2500 Typography \x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500 */"
                   , "  --font-sans: " <> fontStack <> ";"
                   , ""
                   , "  /* \x2500\x2500 Motion \x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500 */"
                   ]
                ++ durationLines mc
                ++ easingLines mc
                ++ [ "}"
                   , ""
                   ]

nougatLines :: DesignGuide -> [Text]
nougatLines dg =
    mapMaybe
        mkLine
        [ ("light-nougat", "  --color-brand-nougat-light: ")
        , ("nougat", "  --color-brand-nougat:       ")
        , ("dark-nougat", "  --color-brand-nougat-dark:  ")
        ]
  where
    mkLine (sid, prop) = case filter (\st -> stId st == sid) (dgSkinTones dg) of
        (st : _) -> Just $ prop <> hexText (stHex st) <> ";"
        _ -> Nothing

semHex :: DesignGuide -> Text -> Text
semHex dg name = case filter (\sc -> scElmName sc == name) (dgSemanticColors dg) of
    (sc : _) -> scHex sc
    _ -> "#000000"

durationLines :: MotionConfig -> [Text]
durationLines mc =
    mapMaybe
        mkLine
        [ ("fast", "  --duration-fast: ")
        , ("base", "  --duration-base: ")
        , ("slow", "  --duration-slow: ")
        ]
  where
    mkLine (name, prop) = case filter (\d -> mdName d == name) (mcDurations mc) of
        (d : _) -> Just $ prop <> T.pack (show (mdMs d)) <> "ms;"
        _ -> Nothing

easingLines :: MotionConfig -> [Text]
easingLines mc =
    mapMaybe
        mkLine
        [ ("standard", "  --ease-standard:   ")
        , ("decelerate", "  --ease-decelerate: ")
        , ("accelerate", "  --ease-accelerate: ")
        ]
  where
    mkLine (name, prop) = case filter (\e -> meName e == name) (mcEasings mc) of
        (e : _) ->
            Just $
                prop
                    <> "cubic-bezier("
                    <> fmtD (meP1x e)
                    <> ", "
                    <> fmtD (meP1y e)
                    <> ", "
                    <> fmtD (meP2x e)
                    <> ", "
                    <> fmtD (meP2y e)
                    <> ");"
        _ -> Nothing

-- ---------------------------------------------------------------------------
-- @utility type-* blocks
-- ---------------------------------------------------------------------------

cssTypeUtilities :: TypographyConfig -> Text
cssTypeUtilities tc =
    T.unlines $
        [ "/* \x2500\x2500 Typography scale \x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500 */"
        , ""
        ]
            ++ concatMap renderTypeUtility (tcScale tc)

renderTypeUtility :: TypeScaleEntry -> [Text]
renderTypeUtility e =
    let name = tseName e
        sr = tseSizeRem e
        w = tseWeight e
        lh = tseLineHeight e
        ls = tseLetterSpacingEm e
        cc = tseCssClass e
     in [ "@utility " <> cc <> " {"
        , "  font-size: " <> fmtD sr <> "rem;"
        , "  font-weight: " <> T.pack (show w) <> ";"
        , "  line-height: " <> fmtD lh <> ";"
        ]
            ++ extraProps name ls
            ++ ["}", ""]
  where
    extraProps "Overline" ls' =
        "  text-transform: uppercase;"
            : ["  letter-spacing: " <> fmtD ls' <> "em;" | ls' /= 0]
    extraProps "Mono" ls' =
        ["  letter-spacing: " <> fmtD ls' <> "em;" | ls' /= 0]
            ++ ["  font-family: ui-monospace, monospace;"]
    extraProps _ ls' =
        ["  letter-spacing: " <> fmtD ls' <> "em;" | ls' /= 0]

-- ---------------------------------------------------------------------------
-- @layer base
-- ---------------------------------------------------------------------------

cssBaseLayer :: Text
cssBaseLayer =
    T.unlines
        [ "/* \x2500\x2500 Base \x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500 */"
        , ""
        , "@layer base {"
        , "  body {"
        , "    font-family: var(--font-sans);"
        , "  }"
        , "}"
        , ""
        ]

-- ---------------------------------------------------------------------------
-- Reduced-motion
-- ---------------------------------------------------------------------------

cssReducedMotion :: Text
cssReducedMotion =
    T.unlines
        [ "/* \x2500\x2500 Reduced-motion \x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500 */"
        , ""
        , "@media (prefers-reduced-motion: reduce) {"
        , "  *, *::before, *::after {"
        , "    animation-duration: 0.01ms !important;"
        , "    transition-duration: 0.01ms !important;"
        , "  }"
        , "  .logo-animated {"
        , "    display: none;"
        , "  }"
        , "}"
        , ""
        ]

-- ---------------------------------------------------------------------------
-- Shared component classes
-- ---------------------------------------------------------------------------

cssSharedComponents :: Text
cssSharedComponents =
    T.unlines
        [ "/* \x2500\x2500 Shared components \x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500\x2500 */"
        , ""
        , "@media (prefers-reduced-motion: no-preference) {"
        , "  .card-hover:hover {"
        , "    transform: translateY(-2px);"
        , "    transition: transform var(--duration-base) var(--ease-standard);"
        , "  }"
        , "}"
        , ""
        , ".timeline-nav {"
        , "  scrollbar-width: thin;"
        , "  scrollbar-color: var(--color-border-default) transparent;"
        , "}"
        , ""
        , ".timeline-nav::-webkit-scrollbar {"
        , "  width: 6px;"
        , "}"
        , ""
        , ".timeline-nav::-webkit-scrollbar-thumb {"
        , "  background-color: var(--color-border-default);"
        , "  border-radius: 3px;"
        , "}"
        ]

-- ---------------------------------------------------------------------------
-- Helpers
-- ---------------------------------------------------------------------------

fmtD :: Double -> Text
fmtD d = T.pack (stripZeros (showFFloat (Just 6) d ""))
  where
    stripZeros s
        | '.' `elem` s = reverse . dropWhile (== '.') . dropWhile (== '0') . reverse $ s
        | otherwise = s
