{-# LANGUAGE OverloadedStrings #-}

{- | Generate src/Guide/Tokens.elm — the single Elm source of truth for all
brand design constants. Modify design-guide.toml, then run @make run@ to
regenerate this file and design-guide.tokens.json together.
-}
module Guide.ElmGen (generateBrandModule) where

import Data.Text (Text)
import Data.Text qualified as T
import Guide.Types

generateBrandModule :: DesignGuide -> Text
generateBrandModule dg =
    let m = dgMeta dg
        tc = dgTypography dg
        sp = dgSpacing dg
        mc = dgMotion dg
        fontStack = T.intercalate ", " (tcFontFamily tc)
     in T.unlines $
            [ "module Guide.Tokens exposing (..)"
            , ""
            , "{-| Generated brand design constants for " <> metaOrganization m <> "."
            , "Do not edit by hand \x2014 regenerate with `make run` from the design-guide repo."
            , "-}"
            , ""
            , "-- Generated by brand-gen. Do not edit by hand."
            , "-- Single Elm source for all brand design constants."
            , "-- To modify: change design-guide.toml, then run `make run`."
            , "-- ---------------------------------------------------------------------------"
            , "-- Organisation"
            , "-- ---------------------------------------------------------------------------"
            , ""
            , ""
            , "associationName : String"
            , "associationName ="
            , "    " <> q (metaOrganization m)
            , ""
            , ""
            , "logoBaseUrl : String"
            , "logoBaseUrl ="
            , "    " <> q (metaCanonicalUrl m)
            , ""
            , ""
            , "designGuideUrl : String"
            , "designGuideUrl ="
            , "    " <> q "/design-guide.tokens.json"
            , ""
            , ""
            , ""
            , "-- ---------------------------------------------------------------------------"
            , "-- Brand colors (primitive)"
            , "-- ---------------------------------------------------------------------------"
            , ""
            , ""
            , "colorBrandBlack : String"
            , "colorBrandBlack ="
            , "    " <> q (hexText (metaFeatureColor m))
            , ""
            , ""
            , "colorBrandWhite : String"
            , "colorBrandWhite ="
            , "    " <> q (hexText (metaHighlightColor m))
            , ""
            , ""
            , "colorBrandYellow : String"
            , "colorBrandYellow ="
            , "    " <> q "#FAC80A"
            , ""
            , ""
            , ""
            , "-- ---------------------------------------------------------------------------"
            , "-- Semantic colors"
            , "-- ---------------------------------------------------------------------------"
            ]
                ++ concatMap renderSemanticColor (dgSemanticColors dg)
                ++ [ "-- ---------------------------------------------------------------------------"
                   , "-- Skin tones"
                   , "-- ---------------------------------------------------------------------------"
                   , ""
                   , ""
                   , "type alias SkinTone ="
                   , "    { id : String, name : String, hex : String }"
                   , ""
                   , ""
                   , "skinTones : List SkinTone"
                   , "skinTones ="
                   , renderSkinToneList (dgSkinTones dg)
                   , ""
                   , ""
                   , ""
                   , "-- ---------------------------------------------------------------------------"
                   , "-- Rainbow"
                   , "-- ---------------------------------------------------------------------------"
                   , ""
                   , ""
                   , "type alias RainbowColor ="
                   , "    { id : String, name : String, hex : String, description : String }"
                   , ""
                   , ""
                   , "rainbowColors : List RainbowColor"
                   , "rainbowColors ="
                   , renderRainbowList (dgRainbowColors dg)
                   , ""
                   , ""
                   , ""
                   , "-- ---------------------------------------------------------------------------"
                   , "-- Typography"
                   , "-- ---------------------------------------------------------------------------"
                   , ""
                   , ""
                   , "fontFamily : String"
                   , "fontFamily ="
                   , "    " <> q fontStack
                   , ""
                   , ""
                   , "fontFile : String"
                   , "fontFile ="
                   , "    " <> q ("/" <> tcFontFile tc)
                   , ""
                   , ""
                   , "type alias TypeStyle ="
                   , "    { name : String"
                   , "    , weight : Int"
                   , "    , sizePx : Int"
                   , "    , sizeRem : Float"
                   , "    , lineHeight : Float"
                   , "    , letterSpacingEm : Float"
                   , "    , cssClass : String"
                   , "    , description : String"
                   , "    }"
                   , ""
                   , ""
                   , "typeScale : List TypeStyle"
                   , "typeScale ="
                   , renderTypeScaleList (tcScale tc)
                   ]
                ++ concatMap renderTypeHelper (tcScale tc)
                ++ [ ""
                   , ""
                   , ""
                   , "-- ---------------------------------------------------------------------------"
                   , "-- Spacing"
                   , "-- ---------------------------------------------------------------------------"
                   , ""
                   , ""
                   , "spacingBaseUnit : Int"
                   , "spacingBaseUnit ="
                   , "    " <> T.pack (show (spcBaseUnit sp))
                   , ""
                   , ""
                   , "type alias SpacingStep ="
                   , "    { name : String, px : Int, rem : Float, tailwindClass : String, description : String }"
                   , ""
                   , ""
                   , "spacingScale : List SpacingStep"
                   , "spacingScale ="
                   , renderSpacingList (spcScale sp)
                   , ""
                   , ""
                   , "pageWrapper : String"
                   , "pageWrapper ="
                   , "    " <> q (spcPageWrapperClass sp)
                   , ""
                   , ""
                   , ""
                   , "-- ---------------------------------------------------------------------------"
                   , "-- Motion"
                   , "-- ---------------------------------------------------------------------------"
                   , ""
                   , ""
                   ]
                ++ concatMap renderMotionDuration (mcDurations mc)
                ++ concatMap renderMotionEasing (mcEasings mc)
                ++ [ ""
                   , "-- ---------------------------------------------------------------------------"
                   , "-- Breakpoints"
                   , "-- ---------------------------------------------------------------------------"
                   , ""
                   , ""
                   , "type alias Breakpoint ="
                   , "    { name : String, px : Int }"
                   , ""
                   , ""
                   , "breakpoints : List Breakpoint"
                   , "breakpoints ="
                   , renderBreakpointList (spcBreakpoints sp)
                   , ""
                   , ""
                   , ""
                   , "-- ---------------------------------------------------------------------------"
                   , "-- Legacy aliases (backward compatibility with Guide.Generated)"
                   , "-- ---------------------------------------------------------------------------"
                   , ""
                   , ""
                   , "featureColor : String"
                   , "featureColor ="
                   , "    colorBrandBlack"
                   , ""
                   , ""
                   , "highlightColor : String"
                   , "highlightColor ="
                   , "    colorBrandWhite"
                   , ""
                   , ""
                   , "darkBackground : String"
                   , "darkBackground ="
                   , "    colorBrandBlack"
                   ]

-- ---------------------------------------------------------------------------
-- Helpers
-- ---------------------------------------------------------------------------

q :: Text -> Text
q t = "\"" <> escElm t <> "\""

escElm :: Text -> Text
escElm = T.concatMap c
  where
    c '\\' = "\\\\"
    c '"' = "\\\""
    c '\n' = "\\n"
    c x = T.singleton x

renderSemanticColor :: SemanticColor -> [Text]
renderSemanticColor sc =
    [ "-- " <> scDescription sc
    , ""
    , ""
    , scElmName sc <> " : String"
    , scElmName sc <> " ="
    , "    " <> q (scHex sc)
    , ""
    , ""
    , scElmName sc <> "Tw : String"
    , scElmName sc <> "Tw ="
    , "    " <> q (scTailwindClass sc)
    , ""
    , ""
    , ""
    ]

renderSkinToneList :: [SkinTone] -> Text
renderSkinToneList [] = "    []"
renderSkinToneList items =
    T.intercalate "\n" $
        ["    [ " <> renderST (head items)]
            ++ map (\i -> "    , " <> renderST i) (tail items)
            ++ ["    ]"]
  where
    renderST st = "{ id = " <> q (stId st) <> ", name = " <> q (stName st) <> ", hex = " <> q (hexText (stHex st)) <> " }"

renderRainbowList :: [RainbowColor] -> Text
renderRainbowList [] = "    []"
renderRainbowList items =
    T.intercalate "\n" $
        ["    [ " <> renderRC (head items)]
            ++ map (\i -> "    , " <> renderRC i) (tail items)
            ++ ["    ]"]
  where
    renderRC rc = "{ id = " <> q (rcId rc) <> ", name = " <> q (rcName rc) <> ", hex = " <> q (hexText (rcHex rc)) <> ", description = " <> q (rcDescription rc) <> " }"

renderTypeScaleList :: [TypeScaleEntry] -> Text
renderTypeScaleList [] = "    []"
renderTypeScaleList items =
    T.intercalate "\n" $
        ["    [ " <> renderTS (head items)]
            ++ map (\i -> "    , " <> renderTS i) (tail items)
            ++ ["    ]"]
  where
    renderTS e =
        "{ name = "
            <> q (tseName e)
            <> ", weight = "
            <> T.pack (show (tseWeight e))
            <> ", sizePx = "
            <> T.pack (show (tseSizePx e))
            <> ", sizeRem = "
            <> T.pack (show (tseSizeRem e))
            <> ", lineHeight = "
            <> T.pack (show (tseLineHeight e))
            <> ", letterSpacingEm = "
            <> T.pack (show (tseLetterSpacingEm e))
            <> ", cssClass = "
            <> q (tseCssClass e)
            <> ", description = "
            <> q (tseDescription e)
            <> " }"

renderTypeHelper :: TypeScaleEntry -> [Text]
renderTypeHelper e =
    [ ""
    , ""
    , ""
    , "-- " <> tseName e <> ": " <> T.pack (show (tseSizePx e)) <> "px / weight " <> T.pack (show (tseWeight e))
    , ""
    , ""
    , "type" <> tseName e <> " : String"
    , "type" <> tseName e <> " ="
    , "    " <> q (tseCssClass e)
    , ""
    , ""
    , "type" <> tseName e <> "Weight : Int"
    , "type" <> tseName e <> "Weight ="
    , "    " <> T.pack (show (tseWeight e))
    ]

renderSpacingList :: [SpacingStep] -> Text
renderSpacingList [] = "    []"
renderSpacingList items =
    T.intercalate "\n" $
        ["    [ " <> renderSP (head items)]
            ++ map (\i -> "    , " <> renderSP i) (tail items)
            ++ ["    ]"]
  where
    renderSP s =
        "{ name = "
            <> q (ssName s)
            <> ", px = "
            <> T.pack (show (ssPx s))
            <> ", rem = "
            <> T.pack (show (ssRem s))
            <> ", tailwindClass = "
            <> q (ssTailwindClass s)
            <> ", description = "
            <> q (ssDescription s)
            <> " }"

renderMotionDuration :: MotionDuration -> [Text]
renderMotionDuration d =
    let name = mdName d
        helperName = "motion" <> T.toUpper (T.take 1 name) <> T.drop 1 name <> "Ms"
     in [ helperName <> " : Int"
        , helperName <> " ="
        , "    " <> T.pack (show (mdMs d))
        , ""
        , ""
        ]

renderMotionEasing :: MotionEasing -> [Text]
renderMotionEasing e =
    let name = meName e
        helperName = "motionEasing" <> T.toUpper (T.take 1 name) <> T.drop 1 name
        cssVal = "cubic-bezier(" <> showD (meP1x e) <> ", " <> showD (meP1y e) <> ", " <> showD (meP2x e) <> ", " <> showD (meP2y e) <> ")"
     in [ helperName <> " : String"
        , helperName <> " ="
        , "    " <> q cssVal
        , ""
        , ""
        ]
  where
    showD d = T.pack (if d == fromIntegral (round d :: Int) then show (round d :: Int) else show d)

renderBreakpointList :: [Breakpoint] -> Text
renderBreakpointList [] = "    []"
renderBreakpointList items =
    T.intercalate "\n" $
        ["    [ " <> renderBP (head items)]
            ++ map (\i -> "    , " <> renderBP i) (tail items)
            ++ ["    ]"]
  where
    renderBP bp = "{ name = " <> q (bpName bp) <> ", px = " <> T.pack (show (bpPx bp)) <> " }"
